### ISSUE TITLE
'&' is not sanitized

### ISSUE THREAD

**Issue by karai17** [leafo/web_sanitize#1]
The official way to sanitize `&` is to convert it to `&amp;`. This is not being performed. There are some use cases for this, for instance if I type the text `&lt;` into a textbox and sanitize it, it santizes to `&lt;` and prints out `<` which is not what I want. I want it to sanitize to `&amp;lt;` which will print out `&lt;`.

**Comment by leafo** [comment]
```
$ cat test.moon 
import sanitize_html from require "web_sanitize"
print sanitize_html "&"

$ moon test.moon 
&amp;
```

The way web sanitize works is that it takes html and stips out bad html, returning safe html. it's not a tool for escaping text for html. Since `&lt;` is safe html it doesn't change it at all.

**Comment by leafo** [comment]
If you're looking to just escape all HTML sequences you can use lapis:

``` moon
import escape from require "lapis.html"
print escape "<div>hello&lt;world</div>"
```

gives

```
&lt;div&gt;hello&amp;lt;world&lt;/div&gt;
```

**Comment by karai17** [comment]
Oh, that could work. How would you write that in Lua?

---

Landon Manning
lmanning17@gmail.com

**Comment by leafo** [comment]
``` lua
local escape = require("lapis.html").escape

print(escape("<hello>"))
```
