### ISSUE TITLE
Could not parse unquoted attribute

### ISSUE THREAD

**Issue by njentit** [leafo/web_sanitize#2]
Example:
`<img src=http://localhost/chicken-small.gif class="small" alt="small chicken">`
parsed attribute: 
- class="small"
- alt="small chicken"
- src=http

the "src" attribute return only "http" part of the attribute.

**Comment by leafo** [comment]
The output of the sanitizer produced by that string is:

```html
&lt;img src=http://localhost/chicken-small.gif class=&quot;small&quot; alt=&quot;small chicken&quot;&gt;
```

Which is correct. I've actually updated the README to speak a bit more about the goals of the sanitizer:

> The sanitizer does not aim to be a complete HTML parser, but instead its goal is to accept a strict subset of HTML and reject everything else. If you want a more complete HTML parser you can use the HTML Parser/Scanner.
